### ISSUE TITLE
Is there a proper way to set the admin password. Using workaround

### ISSUE THREAD

**Issue by tubatodd** [aruba/aos-switch-ansible-collection#14]
I've reached out to HPE/Aruba support with a pretty straightforward ansible question and they weren't able to help. Here's the question, what is the proper way to change the admin password? the `arubaoss_user` package does not support `UT_MANAGER`. Likewise when I use `arubaoss_anycli` the moment the password changes, the session ends and ansible sees that as an unclean exit. 

The best I could come up with was this.

```     - name: "admin password - set password"
       arubaoss_anycli:
         command: "password manager user-name \"admin\" sha1 \"{{ password }}\""
       async: 10
       poll: 2
       ignore_errors: yes
```
The password is set, but because it doesn't exit cleanly, I had to use `ignore_errors: yes` which is not ideal.

**Comment by tchiapuziowong** [comment]
Hi @tubatodd !

You should be able to use the SSH modules to execute CLI commands and use the `prompt` option to match on the prompt that is returned by the switch.

Here is a sample playbook to change the operator password:
```
- name: "Changing passwords on all Aruba switches"
  hosts: all
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Change password
      arubaoss_command:
        commands:
          - command: "configure"
          - command: "password operator user-name test" 
            prompt:
              - ".*New password for operator.*"
              - ".*Re-type.*password for operator.*"
            answer:
              - "newpassword"
              - "newpassword"
```


Here's documentation to help with the `prompt` option:
https://github.com/ansible-collections/ansible.netcommon/blob/main/docs/ansible.netcommon.cli_command_module.rst#examples

Here's a regex checker to check your regular expression in case your playbook fails to match, **make sure to select Python on the left hand side:**
https://regex101.com/

**Comment by tubatodd** [comment]
@tchiapuziowong Thank you for the response. Is there not a rest API equivalent? Our preference is for all configuration to be done via rest calls and not over ssh.

**Comment by tchiapuziowong** [comment]
that can be done with the `arubaoss_user` module like so:
```
---
- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aos_switch
  vars:
  tasks:
    - name: Update manager password
      arubaoss_user:
        user_name: admin
        password_type: "PET_PLAIN_TEXT"
        user_type: UT_MANAGER
        user_password: Aruba123
```

Keep in mind that if you're using the same account that you're trying to reset the password for - the playbook will fail due to not being able to logout properly:
```
fatal: [aoss_1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "body": "<HTML><TITLE>400 Bad Request</TITLE><H1>Bad Request</H1>The REST session timed out. Please login.<P></HTML>",

```


In that case you can add an `ignore_errors: true` to the module but that would prevent ANY errors from being reported.

Some thing to consider
