### ISSUE TITLE
Changing Aruba switch IP for VLAN1

### ISSUE THREAD

**Issue by tubatodd** [aruba/aos-switch-ansible-collection#16]
I am presently working to staging Aruba switches with static IPs on VLAN1. I've seen various examples of using the vlan module to add IP information for VLANs however, setting the IP for VLAN 1 specifically is proving a problem.

I've tried the following
```
      - name: Configure VLAN with IP
        arubaoss_vlan:
          command: config_vlan_ipaddress
          vlan_id: 1
          vlan_ip_address: "{{ ipaddress }}"
          vlan_ip_mask: "{{ netmask }}"
          ip_address_mode: IAAM_STATIC
          vlantype: VT_STATIC_SVLAN
```
When running this task it errors out. After connecting via console, it appears to change from DHCP to static without also assigning the IP.  
```
vlan 1
   name "DEFAULT_VLAN"
   untagged 1-24,27-28,Trk1
   no ip address
   exit
```
I believe when static is added and dhcp removed, it immediately drops the connection before the IP/Mask is applied. 

What is the proper way to get this task done?
