### ISSUE TITLE
REST API modules not able to reach hosts

### ISSUE THREAD

**Issue by Scorcerer** [aruba/aos-switch-ansible-collection#2]
Hi!
the command line modules work great, in this collection, but REST API calls fail like this:
```
fatal: [proper FQDN here]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "None",
            "dns_config_mode": "DCM_MANUAL",
            "dns_domain_names": "",
            "dns_domain_names_2": "",
            "dns_domain_names_3": "",
            "dns_domain_names_4": "",
            "dns_domain_names_5": "",
            "host": null,
            "password": null,
            "port": null,
            "provider": null,
            "server_1": "proper DNS1 IP here",
            "server_2": "proper DNS2 IP here",
            "server_3": "proper DNS3 IP here",
            "server_4": "proper DNS4 IP here",
            "ssh_keyfile": null,
            "timeout": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": false,
            "version_1": "IAV_IP_V4",
            "version_2": "IAV_IP_V4",
            "version_3": "IAV_IP_V4",
            "version_4": "IAV_IP_V4"
        }
    },
    "status": -1,
    "url": "http://None:80/rest/v6.0/login-sessions"
}
```
If/when i installed old aruba_ansible_modules everything worked like a charm.
By removing the files one-by-one i've found that only two of them from old role are actually needed to be installed into python virtual environment:
```
$ mkdir /home/scor/git/ansible/ansible_venv/lib/python3.8/site-packages/ansible/module_utils/network/arubaoss/
$ cp ../aruba-ansible-modules/aruba_module_installer/library/module_utils/network/arubaoss/arubaoss.py /home/scor/git/ansible/ansible_venv/lib/python3.8/site-packages/ansible/module_utils/network/arubaoss/arubaoss.py
$ cp ../aruba-ansible-modules/aruba_module_installer/library/plugins/action/arubaoss.py /home/scor/git/ansible/ansible_venv/lib/python3.8/site-packages/ansible/plugins/action/arubaoss.py
```
My guess is that there's something wrong with REST API modules imports or something, but i don't know enough about python to be sure...
More info also here: https://community.arubanetworks.com/t5/Developer-Community/Using-new-aos-switch-galaxy-collection/td-p/672361

**Comment by tchiapuziowong** [comment]
Hi @Scorcerer !
Some thing that's different in the collection versus our aruba-ansible-modules is you have to include arubaoss in your Network Group Module configuration - please verify you've followed the [Setting Environment Variables](https://github.com/aruba/aos-switch-ansible-collection#setting-environment-variables) section of the [README](https://github.com/aruba/aos-switch-ansible-collection/blob/master/README.md). Please let me know if this doesn't resolve your issue!

**Comment by Scorcerer** [comment]
Hi!
Thanks for response. It looks like this:
```
[defaults]
network_group_modules = arubaoss
```
Well there are some more variable there, but i don't think they're relevant.

Then in ansible-configuration --dump i get:
`NETWORK_GROUP_MODULES(/home/scor/git/ansible/ansible.cfg) = ['arubaoss']`
so it looks right. It's really baffling, as the files seem to be loaded when i use lots of -v's, it's just not using them properly or something.

**Comment by tchiapuziowong** [comment]
Hmm that is strange.. Could you share your inventory file? Without any sensitive information?

**Comment by Scorcerer** [comment]
I'll try to create a small package so all paths will be the same, and then add it here, but it'll take some time.
If i uninstall original modules i'm back to square one with the url containing "none" instead of actual hostname. It's enough to install only those 2 files for action and module_utils, the everything works again.

**Comment by tchiapuziowong** [comment]
You shouldn't need to be copying any additional files over, the collection should have everything you need. What Ansible version are you using?

**Comment by Scorcerer** [comment]
```
ansible 2.9.10
  config file = CUT/ansible/ansible.cfg
  configured module search path = ['CUT/ansible/library']
  ansible python module location = CUT/ansible/ansible_venv/lib/python3.8/site-packages/ansible
  executable location = CUT/ansible/ansible_venv/bin/ansible
  python version = 3.8.5 (default, Sep  5 2020, 10:50:12) [GCC 10.2.0]
```
I just copied the files to test which are causing it to work/not work - i hoped it's gonna help with debugging.
The inventory for host look like this:
```
ansible-inventory --host switch_fqdn --vault-password-file test/fixtures/vault_password_file -i environments/company/env
{
    "ansible_connection": "local",
    "ansible_network_os": "arubanetworks.aos_switch.arubaoss",
    "ansible_password": {
        "__ansible_vault": "$ANSIBLE_VAULT;
	    vaulted_password_here"
    },
    "ansible_user": "manager",
    "dns_server": [
        "$DNS1_IP",
        "$DNS2_IP",
        "$DNS3_IP",
        "$DNS4_IP",
        "$DNS5_IP"
    ],
    "ntp_server": [
        "$NTP1_IP",
        "$NTP2_IP"
    ],
    "syslog_port": 5514,
    "syslog_server": "$syslog_IP"
}
```
Dunno if that's enough, but since we don't store this stuff in files but rather in a tool and it's gonna be hard to replicate it into a file.
The playbook is a very simple one, as we're using roles:
```
- name: Apply switch config
  hosts: all_switches
  gather_facts: no
  serial:
    - "50%"
    - "100%"
  pre_tasks:
    - name: Switch | Check device availability
      wait_for:
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        port: 22
        timeout: 5
      connection: localhost
  tasks:
  - include_role:
      name: switch
    tags:
      - always
```
using pre_tasks to figure out if a switch is online or not, so i don't have to wait on a longer timeout.
And then the primary role file, which except some basic galaxy-info has only this:
```
dependencies:
    - role: switch.aos
      when: ansible_network_os == "arubanetworks.aos_switch.arubaoss"
    - role: switch.brocade
      when: ansible_network_os == "fos"
```
And finally the switch.aos tasks/main.yml:
```
---
- name: Get ArubaOS model and OS version
  vars:
    ansible_connection: network_cli
  arubanetworks.aos_switch.arubaoss_command:
    commands:
      - getmib sysDescr.0
  register: AOS_verion

- name: Configure REST API
  vars:
    ansible_connection: network_cli
  arubanetworks.aos_switch.arubaoss_config:
    before:
      - aaa authentication ssh login public-key
      # - ssh-rsa CUT ansible
    after:
      - web-management ssl

- name: Configure NTP
  vars:
    ansible_connection: network_cli
  arubanetworks.aos_switch.arubaoss_config:
    before:
      - ntp server "{ ntp_server[0] }" iburst
      - ntp server "{ ntp_server[1] }" iburst
      - ntp unicast
      - ntp enable
    after:
      - timesync ntp

- name: Set DNS servers*
  arubanetworks.aos_switch.arubaoss_dns:
    server_1: "{{ dns_server[0] }}"
    server_2: "{{ dns_server[1] }}"
    server_3: "{{ dns_server[2] }}"
    server_4: "{{ dns_server[3] }}"
  register: result
```

**Comment by tchiapuziowong** [comment]
I think we found the issue - This is an Ansible collection - not a role. So in order to use this in a playbook you should specify the collection like so:
```
    ---
    -  hosts: all
       collections:
         - arubanetworks.aos_switch
       tasks:
         - name: Create VLAN 300
           arubaoss_vlan:
             vlan_id: 400
             name: "vlan400"
             config: "create"
             command: config_vlan
```
You can see an example [here](https://github.com/aruba/aos-switch-ansible-collection#example-playbook).

Try that and let me know if that helps!
