### ISSUE TITLE
output of tasks are false "ok"

### ISSUE THREAD

**Issue by LedaxPia** [aruba/aos-switch-ansible-collection#22]
I'm currently working on automating the configuration of our network switches with ansible.
While running a simple Playbook on the switches i became aware of a false positive output from switches that are not even in the network yet. 
The playbook is the following:
```
- hosts: all
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Execute show flash on the switch
      arubaoss_command:
        commands: ['show flash']
```
The inventory looks like this:
```
all:
  children:
    switch:
      hosts:
        switch01:
          ansible_connection: network_cli
          ansible_host: 172.16.XX.XX
          ansible_network_os: arubanetworks.aos_switch.arubaoss
          ansible_password: XXXXXXXXXXXX
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: XXXXXXXXXX
```
All switches are giving back "ok". Only with the verbose parameter i'm seeing that they're failing. 
With the verbose parameter the output of an unreachable switch looks like this:

```
ok: [switch02] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_version": "None", 
            "commands": [
                "show flash"
            ], 
            "host": null, 
            "interval": 1, 
            "match": "all", 
            "output_file": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "retries": 10, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": false, 
            "wait_for": null
        }
    }, 
    "stdout": [
        "[Errno None] Unable to connect to port 22 on 172.16.XX.XXX"
    ], 
    "stdout_lines": [
        [
            "[Errno None] Unable to connect to port 22 on 172.16.XX.XXX"
        ]
    ]
}
```

Is this a known issue?
