### ISSUE TITLE
Using REST API creates an authentication error

### ISSUE THREAD

**Issue by quistian** [aruba/aos-switch-ansible-collection#28]
A test playbook to create a VLAN fails at the authentication phase. It does not seem even to use port 443.

Here's the output:

```
fatal: [2930f_test]: FAILED! => {
    "body": "{\"message\":\"Authentication failed.\"}",
    "changed": false,
    "connection": "close",
    "content-type": "application/json",
    "invocation": {
        "module_args": {
            "acl_direction": null,
            "acl_id": null,
            "acl_type": "AT_STANDARD_IPV4",
            "api_version": "None",
            "command": "config_vlan",
            "config": "create",
            "helper_addresses": "",
            "host": "10.5.9.18",
            "igmp_version": 2,
            "interval": 125,
            "ip_address_mode": "IAAM_STATIC",
            "is_dhcp_server_enabled": false,
            "is_dsnoop_enabled": false,
            "is_igmp_enabled": false,
            "is_jumbo_enabled": false,
            "is_management_vlan": false,
            "is_querier_enabled": true,
            "is_voice_enabled": false,
            "last_member_query_interval": 1,
            "name": "Test VLAN via ssh",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 80,
            "port_id": "",
            "port_mode": "POM_UNTAGGED",
            "provider": {
                "api_version": null,
                "host": "10.5.9.18",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 80,
                "ssh_keyfile": null,
                "timeout": 30,
                "transport": "aossapi",
                "use_proxy": false,
                "use_ssl": false,
                "username": "swbackup",
                "validate_certs": false
            },
            "qos_policy": null,
            "query_max_response_time": 10,
            "robustness": 2,
            "ssh_keyfile": null,
            "status": "VS_PORT_BASED",
            "timeout": 30,
            "use_ssl": false,
            "username": "swbackup",
            "validate_certs": false,
            "version": "IAV_IP_V4",
            "vlan_id": 333,
            "vlan_ip_address": "",
            "vlan_ip_mask": "",
            "vlantype": "VT_STATIC"
        }
    },
    "msg": "HTTP Error 400: Bad Request",
    "requestid": "",
    "server": "eHTTP v2.0",
    "status": 400,
    "transfer-encoding": "chunked",
    "url": "http://10.5.9.18:80/rest/v6.0/login-sessions"
}
```

My inventory file:

```
all:
  vars:
    ansible_network_os: arubanetworks.aos_switch.arubaoss
    ansible_user: swb
    ansible_password: p
    ansible_connection: local  # REST API connection method
  hosts:
    as_dc209_1:
      ansible_host: 10.4.0.215
    2930f_test:
      ansible_host: 10.5.9.18`
```

And my test playbook:

```
     - name: Aruba Switch configuration
    hosts: 2930f_test
    collections:
      - arubanetworks.aos_switch
    tasks:

      - name: create VLAN 333
        arubaoss_vlan:
          vlan_id: 333
          name: "Test VLAN via ssh"
          config: "create"
          command: config_vlan
 ```
      
 And my ansible.cfg file contains:

```
[defaults]
NETWORK_GROUP_MODULES=arubaoss
```

The switch is configured to use radius for authentication
I can log in fine using ssh
