### ISSUE TITLE
Timeout on sample scripts

### ISSUE THREAD

**Issue by GyVVyG** [aruba/aos-switch-ansible-collection#30]
Hello I'm trying to show a PoC for our config management and I'm stuck on our aruba modules (everything else seems to be working OK)
Enviroment:
```
Ubuntu 20.04
ansible [core 2.12.2]
python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
jinja version = 2.10.1
libyaml = True
Aruba 2530-8G-PoEP
Aruba 2530-48G-PoEP 
Aruba 2930F-48G-4SFP+
```
Sample playbook from https://galaxy.ansible.com/arubanetworks/aos_switch :
```
- hosts: all
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Create VLAN 300
      arubaoss_vlan:
        vlan_id: 300
        name: "vlan300"
        config: "create"
        command: config_vlan
- hosts: all
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Execute show run on the switch
      arubaoss_command:
        commands: [show run]
```
with the sample inventory:
```
all:
  hosts:
    swedge:
      ansible_host: xx.xxx.xx.xxx
      ansible_user: xxxxxxx
      ansible_password: xxxxxxx
      ansible_network_os: arubanetworks.aos_switch.arubaoss
      ansible_connection: local
```
And my ansible.cfg
```
[defaults]
NETWORK_GROUP_MODULES = arubaoss
host_key_checking = False
```

Executing will create the VLANs (this is good) and go to the 'show run' command and will timeout. Even if my timeout is at 30, 60 or 120 seconds ( export ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=60 ). I've tried multiple commands and all cli commands gives me a timeout.

```
The full traceback is:
  File "/tmp/ansible_arubaoss_command_payload_agpr6jsc/ansible_arubaoss_command_payload.zip/ansible_collections/arubanetworks/aos_switch/plugins/module_utils/arubaoss.py", line 432, in run_cli_commands
    return conn.run_commands(commands=commands, check_rc=check_rc)
  File "/tmp/ansible_arubaoss_command_payload_agpr6jsc/ansible_arubaoss_command_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [swedge]: FAILED! => {"changed": false, "msg": "command timeout triggered, timeout value is 60 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."}
```

The command I'd like to execute is copy running-config tftp xxx.xx.xx.xx config.txt. Crawling the internet there seems to be multiple different version of the collection, with multiple fonctions what aren't used/support anymore so I'm struggling getting the basics down with the Aruba.

Thanks for any help

**Comment by tchiapuziowong** [comment]
Can you put the command "show run" in quotations like so and see if that changes:
```
    - name: Execute show run on the switch
      arubaoss_command:
        commands: ['show run']
```

**Comment by GyVVyG** [comment]
> 

Haha, It does have ['show run']. This was just because of the formatting when i did the post

**Comment by tchiapuziowong** [comment]
The user you're using to login to execute the `show run` command - do they have manager privileges? Are you able to ssh into the switch directly with that user and execute the same command?

**Comment by GyVVyG** [comment]
> The user you're using to login to execute the `show run` command - do they have manager privileges? Are you able to ssh into the switch directly with that user and execute the same command?

Yes I'm using the manager account.

I've found the solution and the 'examples' are out of date. Looking at the arubaos_command.py ( https://github.com/aruba/aos-switch-ansible-collection/blob/master/plugins/modules/arubaoss_command.py ) It gives us another command which is

```
arubaoss_command:
    commands:
      - 'show run'
      - 'show version'
```

Creating a playbook like this and executing it with -v will output the show running-config in base64. Not bad.

```
---
    -  hosts: all
       collections:
         - arubanetworks.aos_switch
       tasks:
       - name: View the running config in the system
         arubaoss_anycli:
          command: "show running-config"
```

Cheers guys
