### ISSUE TITLE
Unable to backup to TFTP

### ISSUE THREAD

**Issue by haaxema** [aruba/aos-switch-ansible-collection#34]
Hi,

I am starting with the aruba ansible module, it is looking fine but I cant get tftp backup to work.

My playbook looks like this:

```
---
-  hosts: all
   collections:
     - arubanetworks.aos_switch
   vars:
     date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
     filename: "running_config_{{ inventory_hostname }}_{{date}}.txt"
   tasks:
     - name: backup configuration files
       arubaoss_config_bkup:
         file_name: "{{filename}}"
         server_type: ST_TFTP
         server_ip: x.x.x.x
         config_type: CT_STARTUP_CONFIG
```

When I run the playbook it gives the following result:

`RK-SER-A_RK                : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0`

but the config is saved to flash and not to TFTP?

What am I doing wrong?

Martin

**Comment by alagoutte** [comment]
Hi Martin,

What switch version ?

What do you have on switch log ?

**Comment by ershad-ra** [comment]
Hi,
I have the same problem with backup module:
i can restore with from tftp server to swtich flash with this code:
- hosts: XXX
  ignore_errors: true
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Backup configuration files
      arubaoss_config_bkup:
        file_name: "{{ inventory_hostname }}"
        server_type: ST_TFTP
        server_ip: X.X.X.X
        
        
        but when i use this playbook to backup the running config into tftp server, it back it up into the switch, not the tftp server:
        - hosts: XXXX
  ignore_errors: true
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Backup configuration files
      arubaoss_config_bkup:
        file_name: "{{ inventory_hostname }}"
        server_type: ST_TFTP
        server_ip: X.X.X.X
        config_type: CT_RUNNING_CONFIG
        
        my switch model is :
        product_model: HP2530-8G-PoEP Switch(J9774A)
        firmware_version: YA.16.09.0022

**Comment by alagoutte** [comment]
from doc :

```
    config_type:
        description:
            - Type of configuration file. If this option is used, configuration
              file is saved to the system.
        choices: [CT_RUNNING_CONFIG, CT_STARTUP_CONFIG]
```

You need to use arubaoss_command (with copy run tftp...)
