### ISSUE TITLE
arubaoss_dsnoop not handling existing authorized_server

### ISSUE THREAD

**Issue by clevelasosu** [aruba/aos-switch-ansible-collection#39]
```
   - name: Add dsnoop server
     arubaoss_dsnoop:
       use_ssl: true
       port: 443
       command: "authorized_server"
       server_ip: "10.0.0.101"
       config: "create"

```
The first time I run it, it adds the authorized server.  However, on subsequent runs, it errors out:

fatal: [test-2930m]: FAILED! => {"body": "{\"message\":\"Specified authorized_server is already configured\"}", "changed": false, "connection": "close", "content-type": "application/json", "msg": "HTTP Error 400: Bad Request", "requestid": "", "server": "eHTTP v2.0", "status": 400, "transfer-encoding": "chunked", "url": "https://test-2930m:443/rest/v8.0/dsnoop/authorized_server"}

The same thing happens if I try to delete it using config: "delete".  It deletes it the first time, but then errors out the next time:

fatal: [test-2930m]: FAILED! => {"body": "{\n\"message\": \"Error 404: Not Found.\"\n}", "changed": false, "connection": "close", "content-length": "38", "date": "Thu, 01 Jan 1970 03:54:57 GMT", "msg": "HTTP Error 404: Not Found", "requestid": "(null)", "server": "eHTTP v2.0", "status": 404, "url": "https://test-2930m:443/rest/v8.0/dsnoop/authorized_server/10.0.0.101"}
