### ISSUE TITLE
Could not resolve module/action even though it exists

### ISSUE THREAD

**Issue by g-gill1995** [aruba/aos-switch-ansible-collection#4]
---
- hosts: all
  gather_facts: false
  connection: local
  become: yes
  become_method: enable

  collections:
    - arubanetworks.aos_switch

  tasks:
    - name: Show running configuration
      arubanetworks.aos_switch.arubaoss_command:
        commands: ['show run']

When I run in AWX:

ERROR:
ERROR! couldn't resolve module/action 'arubanetworks.aos_switch.arubaoss_command'

I have check ~/.ansible/collections/ansible_collections

I can see arubanetworks/aos_switch/plugins/modules/aubaoss_command.py BUT I still keep getting this error. Making me crazy.

ansible-galaxy collection list does show arubanetworks

**Comment by tchiapuziowong** [comment]
Hi @g-gill1995 thanks for this! There are a couple things to note.

1) When you use the modules inside the playbook you don't preface them with `arubanetwork.aos_switch` so your task should be this:
```yaml
    - name: Show running configuration
      arubaoss_command:
        commands: ['show run']
```
2) For your Ansible connection it should be set to `ansible_connection: network_cli` if you're wanting to use the SSH CLI modules which is what you're using in this case. For more info on how to use these modules and the REST API modules see [Using Both REST API and SSH/CLI Modules on a Host](https://github.com/aruba/aos-switch-ansible-collection#using-both-rest-api-and-sshcli-modules-on-a-host). 
Here is what the final playbook should look like:
```yaml
- hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
  become: yes
  become_method: enable
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Show running configuration
      arubaoss_command:
        commands: ['show run']
```

Please let me know if this resolves your issue!
