### ISSUE TITLE
Firmware Upgrade - Error  No filter named 'find_version'

### ISSUE THREAD

**Issue by Bernhardvleen** [aruba/aos-switch-ansible-collection#45]
Hi, thank you for your effort with this very useful collection.

I am trying to realize firmware updates via ansible. I am currently doing it with the following playbook and inventory (trying to use a local swi):

all:
  hosts:
    aosswitch_1:
      ansible_host: 10.10.0.254
      ansible_user: username
      ansible_password: password
      ansible_connection: local  # REST API connection method
      #ansible_connection: network_cli
      ansible_network_os: arubanetworks.aos_switch.arubaoss  # Do not change
      ansible_python_interpreter: /usr/bin/python3
      primary_ip4: 10.10.10.10

the entry for  primary_ip4 is probably not necessary, I added it to get rid of errors while set_fact section is processed, but not sure if it has any impact (this IP is not in use)

- hosts: all
  collections:
    - arubanetworks.aos_switch
  connection: local
  tasks:
  - name: Login
    include: login_switch.yml

  - name: Upgrade Firmware
    include: firmware_upgrade_api_v3.yml
    vars:
      boot_image: "primary"
      path_to_swi: "YC_16_05_0013.swi" # This will host a HTTP server for you
      state: "downgrade" # pass "downgrade" to downgrade or "current" to stay at same version, default is "upgrade"
      ip: "{{ansible_host}}"
      user: "{{ansible_user}}" 
      password: "{{ansible_password}}"
      enable_sftp: True

after quite some work to get it running I am finally at a stage where I think everything is fine. unfortunately there is an error when not using state: current, which I cannot make sense of. 

I hope you can help!
`
fatal: [aosswitch_1]: FAILED! => {
    "msg": "template error while templating string: No filter named 'find_version'.. String: {{ ((current_firmware.json.result_base64_encoded | b64decode) | replace(\" \", \"\")) | find_version( boot_image )  | replace(\".\",\"_\") }}"
}
`
many thanks in advance, any help is much appreciated! If I can provide you with more info, please let me know.

**Comment by Bernhardvleen** [comment]
aruba 2540 with arubanetworks/aos_switch and all dependencies - things like show running config work

**Comment by tchiapuziowong** [comment]
@Bernhardvleen what is in this file? firmware_upgrade_api_v3 - is that something you created?

**Comment by Bernhardvleen** [comment]
it is the file from github - I just copied it to local path (deactivated the fact check for the second IP)

**Comment by tchiapuziowong** [comment]
Can you share the link ?

**Comment by Bernhardvleen** [comment]
https://github.com/aruba/aruba-switch-ansible/blob/master/aruba_task_lists/aos_switch/firmware_upgrade_api_v3.yml
 is this an official repo?

**Comment by Bernhardvleen** [comment]
set_fact:
    url_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

could have a where clause I think, it always fails in this setup. or am I doing it wrong?

**Comment by tchiapuziowong** [comment]
> https://github.com/aruba/aruba-switch-ansible/blob/master/aruba_task_lists/aos_switch/firmware_upgrade_api_v3.yml is this an official repo?

This repo is deprecated and therefore the workflows are no longer supported- it seems as if you're missing a variable that the workflow is expecting - if you're simply attempting to upload an image to the switch you can do so by using an HTTP server and the module `arubaoss_file_transfer` - you can find the documentation for this module by executing the following `ansible-doc arubanetworks.aos_switch.arubaoss_file_transfer`

I believe what you'll want to do is the following:
```
- hosts: switch1
  collections:
    - arubanetworks.aos_switch
  gather_facts: False
  tasks:

    - name: file copy
      arubaoss_file_transfer:
        file_url: "http://50.1.1.1/check/WC_16_08_REL_YAKIMA_101818.swi"
        file_type: "FTT_FIRMWARE"
        action: "FTA_DOWNLOAD"
        boot_image: "BI_PRIMARY_IMAGE"

    - name: devcie reboot
      arubaoss_reboot:
        boot_image: "BI_PRIMARY_IMAGE"
```
