### ISSUE TITLE
VLAN Options for tagging and voice (aruba 2540)

### ISSUE THREAD

**Issue by Bernhardvleen** [aruba/aos-switch-ansible-collection#46]
Hi, first of all thank you for your effort maintaining this very useful collection!

I am in the process of transferring a pcc config file for an aruba 2540 into playbooks, stumbling over the following options that I have trouble finding the according play options.

untagged 1/2,2/2 (or untagged 1-48) 
tagged Trk1-Trk2

I guess port_mode should be an equivalent to at least one of these - I can not find any more info for the available options 
POM_UNTAGGED, POM_TAGGED_STATIC, POM_FORBIDDEN
can you please point me in the right direction? where can I find more info about those options?

also the option for Voice seems to be missing e.g.
vlan 10
   name "Voice"
   tagged Trk1-Trk2
   no ip address
   voice
   exit

**Comment by alagoutte** [comment]
hi @Bernhardvleen 

for voice vlan, you need to specify when create the vlan

```
     - name: configure vlan with voice
       arubaoss_vlan:
         vlan_id: 10
         name: "vlan10"
         is_voice_enabled: true # <= here
         config: "create"
```

and for tagged use 
```
     - name: configure tagged on trk1,trk2
       arubaoss_vlan:
         vlan_id: 10
         port_id: Trk1,Trk2
         port_mode: POM_TAGGED_STATIC
```

and untagged 
```
     - name: configure tagged on trk1,trk2
       arubaoss_vlan:
         vlan_id: 10
         port_id: 1/2,2/2
         port_mode: POM_UNTAGGED_STATIC
```
