### ISSUE TITLE
arubaoss_interface - missing option for POE (aruba 2540)

### ISSUE THREAD

**Issue by Bernhardvleen** [aruba/aos-switch-ansible-collection#47]
Hi, 
I can not find any option for setting POE active or inactive within the arubaoss_interface.py script.

is there a way to set this on a per interface basis?

many thanks in advance!

**Comment by alagoutte** [comment]
Hi,

it is on https://github.com/aruba/aos-switch-ansible-collection/blob/master/plugins/modules/arubaoss_poe.py

```
     - name: Updates poe port
       arubaoss_poe:
         command: config_poe_port
         port_id: 2
         is_poe_enabled: True
         poe_priority: "PPP_HIGH"
         poe_allocation_method: "PPAM_VALUE"
         allocated_power_in_watts: 15
         port_configured_type: ""
         pre_standard_detect_enabled: False
```
