### ISSUE TITLE
Spanning Tree Option Loop-Guard

### ISSUE THREAD

**Issue by Bernhardvleen** [aruba/aos-switch-ansible-collection#48]
Hi,
I cannot find an option to set loop-guard within the module 
https://github.com/aruba/aos-switch-ansible-collection/blob/master/plugins/modules/arubaoss_stp.py

is there another one that has it?

hopefully the API is complete regarding all available configuration options and no limitation comes from there. 

many thanks in advance for your help!

**Comment by Bernhardvleen** [comment]
I think I have found it - it is not within the interface module but has an extra one 
https://github.com/aruba/aos-switch-ansible-collection/blob/master/plugins/modules/arubaoss_loop_protect.py

**Comment by alagoutte** [comment]
> 
> hopefully the API is complete regarding all available configuration options and no limitation comes from there.
> 
> this is the docu page for it: https://www.arubanetworks.com/techdocs/AOS-CX/10.08/HTML/l2_bridging_4100i-6000-6100-6200/Content/Chp_stp/mstp_cmds/spa-tre-loo-gua.htm
> 
/!\ it is the API doc for Aruba CX not the Aruba OS

**Comment by Bernhardvleen** [comment]
I made an edit to remove the wrong link..

**Comment by Bernhardvleen** [comment]
I am actually reopening this issue, since it is a pity, that there is no option to add the loop-guard option.

atm I have to make an extra task to add it via arubaoss_config which does open me up for ridicule from others. in it self that is no problem, since only my ego is affected, but there is also the component of "why do you use this if it is not complete" - which this awesome collection does not deserve...

current playbook: (untested)

```
- hosts: all
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Set Spanning Tree for Interface "{{ item.int_nr }}"
      arubaoss_stp:
        port_id: "{{ item.int_nr }}"
        is_enable_admin_edge_port: "{{ item.enabled_admin }}"
        is_enable_bpdu_protection: "{{ item.enabled_bpdu }}"
        command: config_spanning_tree_port

    - name: 
      arubaoss_config:
        lines: 
          - spanning-tree "{{ item.int_nr }}" loop-guard
          

      with_item:
        - { int_nr: "1", description: "name", enabled_admin: "true", enabled_bpdu: "true" }
        - { int_nr: "2", description: "name", enabled_admin: "true", enabled_bpdu: "true"  }
        - { int_nr: "3", description: "name", enabled_admin: "true", enabled_bpdu: "true"  }
        - { int_nr: "4", description: "name", enabled_admin: "true", enabled_bpdu: "true"  }
        - { int_nr: "5", description: "name", enabled_admin: "true", enabled_bpdu: "true"  }
        - { int_nr: "6", description: "name", enabled_admin: "true", enabled_bpdu: "true"  }
        - .
        - .
        - .
        - .
```
