### ISSUE TITLE
no module or option to create trunk groups?

### ISSUE THREAD

**Issue by Bernhardvleen** [aruba/aos-switch-ansible-collection#50]
Hi, 
I cannot find any way to create trunk groups other then running the arubaoss_config module and shoot lines via ssh - is that maybe a restriction that comes from the API?

It would be really useful to use Ansible for this action, to be able to have change management possibilities for this as well. 

many thanks in advance for your kind answer!

**Comment by alagoutte** [comment]
You talk about set port on trunk ?

after a quick look on ansible module, not look possible

you can look on REST API ref if there is API available

https://asp.arubanetworks.com/downloads/software/RmlsZTpiNmIwZDM1YS05OWFlLTExZTktODk5MS1kZmIzMTNkZWE5N2I%3D

**Comment by Bernhardvleen** [comment]
yes, it is about something like this. 
```
trunk 49-50 trk1 lacp
trunk 51-52 trk2 lacp
```
thanks for the link!

**Comment by alagoutte** [comment]
> yes, it is about something like this.
> 
> ```
> trunk 49-50 trk1 lacp
> trunk 51-52 trk2 lacp
> ```
> 
> thanks for the link!

Yes, not yet available on this ansible module (or use config module or PowerArubaSW ;-))

**Comment by Bernhardvleen** [comment]
is there an estimate if / when this could be added? (for CX I can not see a module for Trunk definition as well)

**Comment by alagoutte** [comment]
> is there an estimate if / when this could be added? (for CX I can not see a module for Trunk definition as well)

Good question... for @tchiapuziowong  @karthikeyan-dhandapani (it is lag for CX)

**Comment by tchiapuziowong** [comment]
looking into trunk for aos-switch implementation and for AOS-CX the lag interface module is being developed and will be released in an upcoming version

**Comment by tchiapuziowong** [comment]
Hello all! After speaking with development we don't have any REST API support on the switch to configure this feature. At this time we're not implementing any new features within the switch code so there's no planned development to support this. Alternatively you can use our SSH module **arubaoss_config** to execute CLI commands to configure:

```
- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Configure Trunk
      arubaoss_config:
        lines:
          - trunk 14-16 trk1 lacp
        match: line
```
