### ISSUE TITLE
Console output escape characters (sometimes)

### ISSUE THREAD

**Issue by xruth** [aruba/aos-switch-ansible-collection#53]
Hi!

Creating daily backups from switches and pushing it to a Git repo:

```yaml
  vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: arubanetworks.aos_switch.arubaoss
```
```yaml
- hosts: aruba
  serial: 3
  gather_facts: no
  collections:
    - arubanetworks.aos_switch
  tasks:
    - ansible.builtin.include_tasks: backup_aruba_cfg.yml
```
```yaml
- name: Get backup from device
  arubaoss_config:
    backup: yes
    backup_options:
      filename: '{{ inventory_hostname }}.cfg'
      dir_path: /network/aruba/
```
I notice that sometimes escape characters are shown in the output causing a change in Git. A couple of backups later they disappear only to show up again after some time.

Diff from Git:
```
- vlan 1821
+ [24;1Hvlan 1821
```
```
- [24;1Hvlan 1821
+ vlan 1821
```
Not sure if this has to do with your collection though but I thought I will let you know. 

Best!
Michael
