### ISSUE TITLE
"msg": "Negative size passed to PyBytes_FromStringAndSize"

### ISSUE THREAD

**Issue by ershad-ra** [aruba/aos-switch-ansible-collection#57]
Hello there,
I am trying to do the following with cli_command module:
```
- hosts: SW-B
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Upload Image to secondary flash and reboot the switch
      arubaoss_command:
        commands:
          - command: "copy tftp flash X.X.X.X YA_16_11_0008.swi secondary"
            prompt:
              - "Continue (y/n)?"
            answer:
              - y
    - name: Boot on the new secondary Image
      arubaoss_command:
        commands:
          - command: "boot system flash secondary"
            prompt:
              - "Continue (y/n)?"
            answer:
              - y
```
- upload a YA_16_11_008 into secondary flash of a aos switch that has YA_15_18_xxx image
- boot the switch into secondary image
the image uploads and the switch reboots but i get a fatal error on the boot task:

```
PLAY [SW-BA0-1] *************************************************************

TASK [Gathering Facts] ********************************************************
ok: [SW-BA0-1]

TASK [Upload Image to secondary flash and reboot the switch] ********************************************************************************
ok: [SW-BA0-1]

TASK [Boot on the new secondary Image] ***********************************
fatal: [SW-BA0-1]: FAILED! => {"changed": false, "msg": "Negative size passed to PyBytes_FromStringAndSize"}

PLAY RECAP *******************************************************************
SW-BA0-1                   : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
does anyone have any idea why i am getting this error?
**the switch is:
2530-48G (J9775A)**

thanks in advance

**Comment by alagoutte** [comment]
What do you have if you enable more verbose ?

**Comment by tchiapuziowong** [comment]
@ershad-ra this is expected due to the SSH module searching for/expecting to receive the switch prompt after a command is finished - in this case it's receiving the bytes due to the reboot. A workaround is to change the criteria of when the module fails like so:
```
    - name: Reboot Switch
      arubaoss_command:
        commands:
          - command: "boot system flash primary"
            check_all: true
            prompt:
              - '.*\(y\/n\)\?.*'
              - '.*\(y\/n\)\?.*'
            answer:
              - 'y'
              - 'y'
      register: result
      failed_when: '"Negative size passed to PyBytes_FromStringAndSize" not in result.msg'
      # it will error because characters are returned instead of expected prompt
	  # so you must define a specific failure
```
