### ISSUE TITLE
keep getting error accessing aruba/procurve switch to run backup script

### ISSUE THREAD

**Issue by hphan082-code** [aruba/aos-switch-ansible-collection#94]
hello,
I'm new so please be gentle. ;) 
I'm running ansible on a docker container, and trying to run ansible playbook to backup our procurve/aruba collection of switches.

This is my inventory
```
all:
  hosts:
    switch1:
      ansible_host: 192.168.x.x
      ansible_user: _fillin_
      ansible_password: _fillin_
      ansible_connection: network_cli
      ansible_network_os: arubanetworks.aos_switch.arubaoss
```

and this is my yml file

```
- hosts: all
  collections:
    - arubanetworks.aos_switch
  gather_facts: no
  
  vars:
    ansible_connection: network_cli
    ansible_network_cli_ssh_type: libssh
  tasks:
    - name: Backup config to local file
      arubaoss_config:
        backup: True
        backup_options:
          filename: backup.txt
          dir_path: /path/to

```

I confirmed I have pylibssh installed, and keep getting "unable to retrieve current co" error.

I confirmed that from the container, if I ssh to the switch, I can get to it normally.
